Repository CarletonU-2223-SAV/SYSC4806-Project, pull requests merged in 2023-03, with the labels that each got.

#12 Project model
  pom.xml
  src/main/java/com/groupseven/sysc4806project/Book.java
  src/main/java/com/groupseven/sysc4806project/ShoppingCart.java
  src/main/java/com/groupseven/sysc4806project/User.java
  src/test/java/com/groupseven/sysc4806project/BookTest.java
  src/test/java/com/groupseven/sysc4806project/ShoppingCartTest.java
  src/test/java/com/groupseven/sysc4806project/UserTest.java
Labels: feature

#13 Implement RestController for Book
  src/main/java/com/groupseven/sysc4806project/Book.java
  src/main/java/com/groupseven/sysc4806project/BookRepository.java
  src/main/java/com/groupseven/sysc4806project/BookService.java
  src/test/java/com/groupseven/sysc4806project/BookTest.java
Labels: feature

#14 Develop home page with header template
  book-img/.gitignore
  book-img/default.png
  pom.xml
  src/main/java/com/groupseven/sysc4806project/Book.java
  src/main/java/com/groupseven/sysc4806project/BookService.java
  src/main/java/com/groupseven/sysc4806project/BookstoreController.java
  src/main/java/com/groupseven/sysc4806project/ImageController.java
  src/main/java/com/groupseven/sysc4806project/ImageService.java
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/test/java/com/groupseven/sysc4806project/BookTest.java
  src/test/java/com/groupseven/sysc4806project/HttpTest.java
  src/test/java/com/groupseven/sysc4806project/Sysc4806ProjectApplicationTests.java
Labels: feature

#15 Fix error messages on server launch
  src/main/java/com/groupseven/sysc4806project/User.java
Labels: bug

#17 Add edit book page
  src/main/java/com/groupseven/sysc4806project/BookService.java
  src/main/java/com/groupseven/sysc4806project/BookstoreController.java
  src/main/resources/templates/add-edit.html
  src/main/resources/templates/index.html
  src/test/java/com/groupseven/sysc4806project/BookTest.java
  src/test/java/com/groupseven/sysc4806project/HttpTest.java
Labels: feature

#18 Change DB to sqlite
  .gitignore
  pom.xml
  src/main/resources/application.properties
Labels: feature

#19 Update the readme and include the database schema
  README.md
  doc/class_diagram.png
  doc/database_schema.png
Labels: documentation

#20 Handle uploading/deleting images and style edit page
  src/main/java/com/groupseven/sysc4806project/BookService.java
  src/main/java/com/groupseven/sysc4806project/BookstoreController.java
  src/main/java/com/groupseven/sysc4806project/ImageService.java
  src/main/resources/templates/add-edit.html
Labels: feature

#21 Implemented Shopping Cart Page
  src/main/java/com/groupseven/sysc4806project/BookstoreController.java
  src/main/java/com/groupseven/sysc4806project/ShoppingCartController.java
  src/main/java/com/groupseven/sysc4806project/ShoppingCartService.java
  src/main/resources/templates/cart-page.html
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/test/java/com/groupseven/sysc4806project/HttpTest.java
Labels: feature

#30 Run tests in memory DB
  pom.xml
  src/test/resources/application.properties
Labels: feature

#31 Refactor User Model to hold Shopping Cart
  doc/class_diagram.png
  doc/database_schema.png
  src/main/java/com/groupseven/sysc4806project/BookstoreController.java
  src/main/java/com/groupseven/sysc4806project/ShoppingCart.java
  src/main/java/com/groupseven/sysc4806project/ShoppingCartController.java
  src/main/java/com/groupseven/sysc4806project/ShoppingCartRepository.java
  src/main/java/com/groupseven/sysc4806project/ShoppingCartService.java
  src/main/java/com/groupseven/sysc4806project/User.java
  src/main/java/com/groupseven/sysc4806project/UserService.java
  src/main/resources/templates/cart-page.html
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/test/java/com/groupseven/sysc4806project/HttpTest.java
  src/test/java/com/groupseven/sysc4806project/ShoppingCartTest.java
  src/test/java/com/groupseven/sysc4806project/UserTest.java
Labels: refactor

#35 Added Purchase History of Books to User Model
  src/main/java/com/groupseven/sysc4806project/User.java
  src/test/java/com/groupseven/sysc4806project/UserTest.java
Labels: refactor

#39 Added book genre
  src/main/java/com/groupseven/sysc4806project/Book.java
  src/main/java/com/groupseven/sysc4806project/BookRepository.java
  src/main/java/com/groupseven/sysc4806project/BookService.java
  src/main/java/com/groupseven/sysc4806project/BookstoreController.java
  src/main/resources/templates/add-edit.html
  src/main/resources/templates/index.html
  src/test/java/com/groupseven/sysc4806project/BookTest.java
  src/test/java/com/groupseven/sysc4806project/HttpTest.java
Labels: feature

#37 Create active user
  src/main/java/com/groupseven/sysc4806project/BookstoreController.java
  src/main/java/com/groupseven/sysc4806project/ShoppingCartController.java
  src/main/java/com/groupseven/sysc4806project/UserController.java
  src/main/java/com/groupseven/sysc4806project/UserRepository.java
  src/main/java/com/groupseven/sysc4806project/UserService.java
  src/main/resources/templates/cart-page.html
  src/main/resources/templates/header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/sign-up.html
  src/test/java/com/groupseven/sysc4806project/HttpTest.java
  src/test/java/com/groupseven/sysc4806project/UserTest.java
Labels: feature

#40 Recommendation
  src/main/java/com/groupseven/sysc4806project/BookService.java
  src/main/java/com/groupseven/sysc4806project/User.java
  src/main/java/com/groupseven/sysc4806project/UserController.java
  src/main/java/com/groupseven/sysc4806project/UserService.java
  src/main/resources/templates/header.html
  src/main/resources/templates/recommendation.html
  src/test/java/com/groupseven/sysc4806project/HttpTest.java
  src/test/java/com/groupseven/sysc4806project/UserTest.java
Labels: feature

#41 Configure the project for Azure
  src/main/java/com/groupseven/sysc4806project/ShoppingCartController.java
  src/main/resources/templates/cart-page.html
Labels: feature

#43 Update readme and diagrams for milestone 2
  README.md
  doc/class_diagram.png
  doc/database_schema.png
Labels: documentation
