Repository CarletonU-2223-SAV/SYSC4806-Project, pull requests merged in 2023-04, with the labels that each got.

#57 Image test
  src/test/java/com/groupseven/sysc4806project/ImageControllerTest.java
  src/test/resources/default.png
Labels: refactor

#53 Move book HTTP tests to BookTest
  src/test/java/com/groupseven/sysc4806project/BookServiceTest.java
  src/test/java/com/groupseven/sysc4806project/BookTest.java
  src/test/java/com/groupseven/sysc4806project/BookstoreControllerTest.java
  src/test/java/com/groupseven/sysc4806project/HttpTest.java
Labels: refactor

#58 Jaccard recommendation
  src/main/java/com/groupseven/sysc4806project/User.java
  src/main/java/com/groupseven/sysc4806project/UserController.java
  src/main/java/com/groupseven/sysc4806project/UserService.java
  src/test/java/com/groupseven/sysc4806project/HttpTest.java
  src/test/java/com/groupseven/sysc4806project/UserTest.java
Labels: feature

#59 Split User Integration Tests
  src/test/java/com/groupseven/sysc4806project/HttpTest.java
  src/test/java/com/groupseven/sysc4806project/UserControllerTest.java
  src/test/java/com/groupseven/sysc4806project/UserServiceTest.java
  src/test/java/com/groupseven/sysc4806project/UserTest.java
Labels: refactor

#55 Splitting shopping cart controller test into it's own test class
  src/test/java/com/groupseven/sysc4806project/ShoppingCartControllerTest.java
Labels: refactor

#54 Simplify Azure function call
  src/main/java/com/groupseven/sysc4806project/ShoppingCartController.java
Labels: refactor

#60 Add shipping timeline and order confirmation
  src/main/java/com/groupseven/sysc4806project/ShoppingCartController.java
  src/main/resources/templates/checkout-page.html
  src/main/resources/templates/confirm-checkout.html
  src/test/java/com/groupseven/sysc4806project/ShoppingCartControllerTest.java
Labels: feature

#62 Update readme and diagrams for milestone 3
  README.md
  doc/class_diagram.png
  doc/database_schema.png
Labels: documentation
